apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: template-api-hpa-production
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: template-api-production
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 500Mi
